[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
optimizer = true
optimizer_runs = 200
verbosity = 2
gas_reports = ["*"]
auto_detect_solc = false

# Remappings for OpenZeppelin
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# RPC endpoints for testing and deployment
[rpc_endpoints]
ethereum = "${ETH_RPC_URL}"
arbitrum = "${ARB_RPC_URL}"
optimism = "${OP_RPC_URL}"

# Test configuration
[profile.default.fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
